swagger: '2.0'
info:
  $ref: ./info/index.yaml
host: sandbox.taxitime.com
basePath: /
tags:
  - name: Booking
    description: List of the operations involved in the booking of a vehicle.
  - name: User
    description: List of the operations dealing with users.
  - name: Auth
    description: List of the operations dealing credentials and tokens.
schemes:
  - https
paths:
  $ref: ./paths/index.yaml

definitions:
  $ref: ./definitions/index.yaml

parameters:
  $ref: ./parameters/index.yaml
